In [13]:
import pandas as pd
from itertools import product, permutations

scenario = pd.DataFrame(
    data={
        "Job": [1, 2, 3, 4, 5],
        "t_i": [10, 8, 6, 7, 4],
        "d_i": [15, 20, 10, 30, 12],
        "h_i": [3, 2, 5, 4, 6],
        "c_i": [10, 22, 10, 8, 15],
    },
).set_index("Job")

scenario

     t_i  d_i  h_i  c_i
Job
1     10   15    3   10
2      8   20    2   22
3      6   10    5   10
4      7   30    4    8
5      4   12    6   15

In [25]:
jobs = scenario.index.tolist()
possible_routes = [*permutations(jobs)]
possible_routes[0]

(1, 2, 3, 4, 5)

In [48]:
from tracemalloc import start


def calculate_cost(
    job_done: int,
    current_time: int,
) -> int:
    h = scenario.loc[job_done, "h_i"]
    c = scenario.loc[job_done, "c_i"]

    time_limit = scenario.loc[job_done, "d_i"]

    time_retention = max(0, time_limit - current_time)
    time_delay = max(0, current_time - time_limit)

    retention_cost = time_retention * h
    penalizat_cost = time_delay * c

    return retention_cost + penalizat_cost


def path_name(path: tuple[str]) -> str:
    path_str = [str(job) for job in path]
    path_str = "".join(path_str)

    return path_str


def FO(path: tuple[int], scenario: pd.DataFrame) -> int:
    path_str = [str(job) for job in path]
    path_str = "".join(path_str)

    start_point = path[0]

    current_time = scenario.loc[start_point, "t_i"]
    cost = calculate_cost(job_done=start_point, current_time=current_time)
    for next_job in path[1:]:
        # print(f"Current Cost: {cost}")
        current_time += scenario.loc[next_job, "t_i"]

        cost += calculate_cost(
            job_done=next_job,
            current_time=current_time,
        )

    return cost
    ...

In [49]:
solutions = {
    path_name(path): 1 / FO(path=path, scenario=scenario) for path in possible_routes
}
solutions

Current Cost: 512
Current Cost: 439
Current Cost: 594
Current Cost: 544
Current Cost: 389
Current Cost: 423
Current Cost: 516
Current Cost: 443
Current Cost: 690
Current Cost: 658
Current Cost: 411
Current Cost: 537
Current Cost: 732
Current Cost: 682
Current Cost: 784
Current Cost: 752
Current Cost: 650
Current Cost: 702
Current Cost: 309
Current Cost: 343
Current Cost: 361
Current Cost: 487
Current Cost: 529
Current Cost: 581
Current Cost: 547
Current Cost: 474
Current Cost: 629
Current Cost: 579
Current Cost: 424
Current Cost: 458
Current Cost: 507
Current Cost: 434
Current Cost: 605
Current Cost: 495
Current Cost: 324
Current Cost: 374
Current Cost: 739
Current Cost: 689
Current Cost: 699
Current Cost: 589
Current Cost: 579
Current Cost: 539
Current Cost: 314
Current Cost: 348
Current Cost: 274
Current Cost: 324
Current Cost: 458
Current Cost: 418
Current Cost: 471
Current Cost: 398
Current Cost: 645
Current Cost: 613
Current Cost: 366
Current Cost: 492
Current Cost: 475
Current Cost: 402
Current Cost: 573
Current Cost: 463
Current Cost: 292
Current Cost: 342
Current Cost: 755
Current Cost: 723
Current Cost: 615
Current Cost: 505
Current Cost: 613
Current Cost: 473
Current Cost: 298
Current Cost: 424
Current Cost: 206
Current Cost: 256
Current Cost: 534
Current Cost: 394
Current Cost: 777
Current Cost: 727
Current Cost: 829
Current Cost: 797
Current Cost: 695
Current Cost: 747
Current Cost: 757
Current Cost: 707
Current Cost: 717
Current Cost: 607
Current Cost: 597
Current Cost: 557
Current Cost: 789
Current Cost: 757
Current Cost: 649
Current Cost: 539
Current Cost: 647
Current Cost: 507
Current Cost: 606
Current Cost: 658
Current Cost: 490
Current Cost: 450
Current Cost: 618
Current Cost: 478
Current Cost: 315
Current Cost: 349
Current Cost: 367
Current Cost: 493
Current Cost: 535
Current Cost: 587
Current Cost: 354
Current Cost: 388
Current Cost: 314
Current Cost: 364
Current Cost: 498
Current Cost: 458
Current Cost: 314
Current Cost: 440
Current Cost: 222
Current Cost: 272
Current Cost: 550
Current Cost: 410
Current Cost: 632
Current Cost: 684
Current Cost: 516
Current Cost: 476
Current Cost: 644
Current Cost: 504

{'12345': 0.001953125,
 '12354': 0.002277904328018223,
 '12435': 0.0016835016835016834,
 '12453': 0.001838235294117647,
 '12534': 0.002570694087403599,
 '12543': 0.002364066193853428,
 '13245': 0.001937984496124031,
 '13254': 0.002257336343115124,
 '13425': 0.0014492753623188406,
 '13452': 0.001519756838905775,
 '13524': 0.0024330900243309003,
 '13542': 0.00186219739292365,
 '14235': 0.001366120218579235,
 '14253': 0.001466275659824047,
 '14325': 0.0012755102040816326,
 '14352': 0.0013297872340425532,
 '14523': 0.0015384615384615385,
 '14532': 0.0014245014245014246,
 '15234': 0.003236245954692557,
 '15243': 0.0029154518950437317,
 '15324': 0.002770083102493075,
 '15342': 0.002053388090349076,
 '15423': 0.001890359168241966,
 '15432': 0.0017211703958691911,
 '21345': 0.0018281535648994515,
 '21354': 0.002109704641350211,
 '21435': 0.001589825119236884,
 '21453': 0.0017271157167530224,
 '21534': 0.0023584905660377358,
 '21543': 0.002183406113537118,
 '23145': 0.0019723865877712033,
 '23154': 0.002304147465437788,
 '23415': 0.001652892561983471,
 '23451': 0.00202020202020202,
 '23514': 0.0030864197530864196,
 '23541': 0.00267379679144385,
 '24135': 0.0013531799729364006,
 '24153': 0.001451378809869376,
 '24315': 0.001430615164520744,
 '24351': 0.001697792869269949,
 '24513': 0.0017271157167530224,
 '24531': 0.0018552875695732839,
 '25134': 0.0031847133757961785,
 '25143': 0.0028735632183908046,
 '25314': 0.0036496350364963502,
 '25341': 0.0030864197530864196,
 '25413': 0.002183406113537118,
 '25431': 0.0023923444976076554,
 '31245': 0.0021231422505307855,
 '31254': 0.002512562814070352,
 '31425': 0.0015503875968992248,
 '31452': 0.0016313213703099511,
 '31524': 0.00273224043715847,
 '31542': 0.0020325203252032522,
 '32145': 0.002105263157894737,
 '32154': 0.0024875621890547263,
 '32415': 0.0017452006980802793,
 '32451': 0.0021598272138228943,
 '32514': 0.003424657534246575,
 '32541': 0.0029239766081871343,
 '34125': 0.0013245033112582781,
 '34152': 0.0013831258644536654,
 '34215': 0.0016260162601626016,
 '34251': 0.0019801980198019802,
 '34512': 0.0016313213703099511,
 '34521': 0.0021141649048625794,
 '35124': 0.003355704697986577,
 '35142': 0.0023584905660377358,
 '35214': 0.0048543689320388345,
 '35241': 0.00390625,
 '35412': 0.0018726591760299626,
 '35421': 0.0025380710659898475,
 '41235': 0.001287001287001287,
 '41253': 0.001375515818431912,
 '41325': 0.0012062726176115801,
 '41352': 0.0012547051442910915,
 '41523': 0.0014388489208633094,
 '41532': 0.0013386880856760374,
 '42135': 0.001321003963011889,
 '42153': 0.0014144271570014145,
 '42315': 0.001394700139470014,
 '42351': 0.0016474464579901153,
 '42513': 0.0016750418760469012,
 '42531': 0.0017953321364452424,
 '43125': 0.0012674271229404308,
 '43152': 0.001321003963011889,
 '43215': 0.0015408320493066256,
 '43251': 0.0018552875695732839,
 '43512': 0.0015455950540958269,
 '43521': 0.0019723865877712033,
 '45123': 0.0016501650165016502,
 '45132': 0.001519756838905775,
 '45213': 0.0020408163265306124,
 '45231': 0.0022222222222222222,
 '45312': 0.0016181229773462784,
 '45321': 0.0020920502092050207,
 '51234': 0.0031746031746031746,
 '51243': 0.0028653295128939827,
 '51324': 0.0027247956403269754,
 '51342': 0.002028397565922921,
 '51423': 0.001869158878504673,
 '51432': 0.0017035775127768314,
 '52134': 0.002824858757062147,
 '52143': 0.002577319587628866,
 '52314': 0.0031847133757961785,
 '52341': 0.0027472527472527475,
 '52413': 0.002008032128514056,
 '52431': 0.002183406113537118,
 '53124': 0.0031847133757961785,
 '53142': 0.0022727272727272726,
 '53214': 0.0045045045045045045,
 '53241': 0.003676470588235294,
 '53412': 0.0018181818181818182,
 '53421': 0.0024390243902439024,
 '54123': 0.0015822784810126582,
 '54132': 0.0014619883040935672,
 '54213': 0.001937984496124031,
 '54231': 0.0021008403361344537,
 '54312': 0.0015527950310559005,
 '54321': 0.001984126984126984}

In [52]:
max(solutions, key=solutions.get)

'35214'

In [55]:
solutions["35214"]

0.0048543689320388345

In [ ]:
calculate_cost((3, 5, 2, 1, 4))

In [56]:
FO(path=(3, 5, 2, 1, 4), scenario=scenario)

Current Cost: 206

206